### ISSUE TITLE
RuntimeError: Given input size: (64x1x160000). Calculated output size: (64x0x80000). Output size is too small

### ISSUE THREAD

**Issue by HorizonWind2004** [cyh-0/CAVP#10]
My audio tensor is `torch.Size([1, 1, 160000])`, and the test command is:

```
Traceback (most recent call last):
  File "/home/yanhao/coco/CAVP/test_avss_resize.py", line 291, in <module>
    main(0, hyp_param.gpus, hyp_param)
  File "/home/yanhao/coco/CAVP/test_avss_resize.py", line 237, in main
    trainer.test(model_v, model_a, -1, test_loader)
  File "/home/yanhao/miniconda3/envs/ssl/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/yanhao/coco/CAVP/trainer/trainer_cavp_avs_obj.py", line 326, in test
    model_v_(image, spec, eval_mode=True)
  File "/home/yanhao/miniconda3/envs/ssl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yanhao/coco/CAVP/models/cavp_model.py", line 203, in forward
    return self.forward_inference(image, audio)
  File "/home/yanhao/coco/CAVP/models/cavp_model.py", line 194, in forward_inference
    fea_a = self.audio_backbone(audio)
  File "/home/yanhao/miniconda3/envs/ssl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yanhao/coco/CAVP/models/audio/audio_network.py", line 34, in forward
    return self.backbone(x)
  File "/home/yanhao/miniconda3/envs/ssl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yanhao/coco/CAVP/models/audio/backbones/vgg.py", line 18, in forward
    x = self.features(x)
  File "/home/yanhao/miniconda3/envs/ssl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yanhao/miniconda3/envs/ssl/lib/python3.10/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/yanhao/miniconda3/envs/ssl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yanhao/miniconda3/envs/ssl/lib/python3.10/site-packages/torch/nn/modules/pooling.py", line 162, in forward
    return F.max_pool2d(input, self.kernel_size, self.stride,
  File "/home/yanhao/miniconda3/envs/ssl/lib/python3.10/site-packages/torch/_jit_internal.py", line 423, in fn
    return if_false(*args, **kwargs)
  File "/home/yanhao/miniconda3/envs/ssl/lib/python3.10/site-packages/torch/nn/functional.py", line 782, in _max_pool2d
    return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: Given input size: (64x1x160000). Calculated output size: (64x0x80000). Output size is too small
```

`python test_avss_resize.py --setup avss_binary --avsbench_split v1s --resize_flag`

It goes wrong in the max_pool2d, how to solve this problem?

**Comment by cyh-0** [comment]
Hi, 

The vgg itself takes the mel-spectrogram as the input. We need to use ``self.preprocess_audio`` function to convert the waveform to Mel-Spectrogram. Hence, the dimensionality of ``audio`` that enters the ``self.audio_backbone`` would be ``[B, 1, 96, 64]``.

Cheers,

**Comment by HorizonWind2004** [comment]
Thank you! I still have two question.

1) There is a bug in test_avss_resize.py:

```python
    ckpt = torch.load("./cavp_avsobj_ms.pth")['model']
    ckpt = {k.replace("module.", ""): v for k, v in ckpt.items()} # without this line, the state_dict will not be loaded.
    model_v.load_state_dict(ckpt, strict=False)
```

2) Can you give a trained CAVP on VPO_MSMI? My RTX3090 cannot handle the default training setting.

**Comment by cyh-0** [comment]
Hi,

The model was wrapped in the DataParallel module when it was saved to .pth. You can use ``model_v = nn.DataParallel(model_v, device_ids=["cuda:0"])`` before loading the checkpoint to avoid the loading error.

You can find the VPO checkpoint in [here](https://drive.google.com/file/d/1xmEFzwLVPtiJpu-75gzcsqlXgYfwaQcN/view?usp=sharing).

Cheers

**Comment by HorizonWind2004** [comment]
Thank you for excellent work!
