### ISSUE TITLE
Problem Of Training

### ISSUE THREAD

**Issue by ButlerZOH** [cyh-0/CAVP#5]
epoch 0:  l_ce 0.396  l_ctr_av 4.032: 100%|███████████████████████████████████████| 4190/4190 [1:06:57<00:00,  1.04it/s]
  0%|                                                                                          | 0/1437 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/home/friends/yinhao/code/CAVP/main_vpo_stereo.py", line 282, in <module>
    main(0, hyp_param.gpus, hyp_param)
  File "/home/friends/yinhao/code/CAVP/main_vpo_stereo.py", line 237, in main
    trainer.validation(model_v, model_a, epoch, test_loader)
  File "/home/friends/yinhao/anaconda3/envs/QwenAudio/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/friends/yinhao/code/CAVP/trainer/trainer_cavp_vpo_stereo.py", line 316, in validation
    (
ValueError: too many values to unpack (expected 2)

**Comment by cyh-0** [comment]
Hi @ButlerZOH,

Thanks for raising the issue. I have modified the inference code at the [line](https://github.com/cyh-0/CAVP/blob/b19de09e6536c348f77d8fb259aaf3345df734cb/trainer/trainer_cavp_vpo_stereo.py#L319)

**Comment by ButlerZOH** [comment]
Traceback (most recent call last):
  File "/home/friends/yinhao/code/CAVP/main_vpo_stereo.py", line 282, in <module>
    main(0, hyp_param.gpus, hyp_param)
  File "/home/friends/yinhao/code/CAVP/main_vpo_stereo.py", line 233, in main
    trainer.train(model_v, model_a, optimizer_v, optimizer_a, epoch, train_loader)
  File "/home/friends/yinhao/code/CAVP/trainer/trainer_cavp_vpo_stereo.py", line 212, in train
    output_cat, ctr_feature_cat, _ = model_v_(image, audio, shuffle_info, ow_flag, audio_func=True)
  File "/home/friends/yinhao/anaconda3/envs/QwenAudio/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/friends/yinhao/anaconda3/envs/QwenAudio/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/friends/yinhao/anaconda3/envs/QwenAudio/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 183, in forward
    return self.module(*inputs[0], **module_kwargs[0])
  File "/home/friends/yinhao/anaconda3/envs/QwenAudio/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/friends/yinhao/anaconda3/envs/QwenAudio/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/friends/yinhao/code/CAVP/models/cavp_model.py", line 206, in forward
    return self.forward_train(image, audio, shuffle_info, ow_flag, audio_func=audio_func)
  File "/home/friends/yinhao/code/CAVP/models/cavp_model.py", line 181, in forward_train
    fea_a = self.forward_audio(audio, shuffle_info, ow_flag)
  File "/home/friends/yinhao/code/CAVP/models/cavp_model.py", line 164, in forward_audio
    shuffle_fea_a = self.memory.overwrite_audio_feature(
  File "/home/friends/yinhao/anaconda3/envs/QwenAudio/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CAVP' object has no attribute 'memory'

**Comment by cyh-0** [comment]
Hi @ButlerZOH ,

I have updated the file.
